---
abstract: 'Convert RGB color to HSI (hue saturation intensity) color-space'
author:
  - 'Renato Cron <rentocron@cpan.org>'
build_requires:
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RGB2HSI
requires:
  Exporter: 0
  strict: 0
version: 0.01
